name: Process FRMR Docs to OSCAL

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  process-frmr:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit and push changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r FR_docs_to_OSCAL/requirements.txt

    - name: Process FRMR files and generate OSCAL
      run: |
        python FR_docs_to_OSCAL/process_frmr_to_oscal.py

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain OSCAL/)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add OSCAL/
        git commit -m "Auto-update: Process FRMR docs and generate OSCAL files [skip ci]"
        git push
